import { createHash } from "crypto";

import { FA_CREW_NAME, isFaCrew, withFaCrew } from "./crews";
import { applyGuestbookVote, type GuestbookVote } from "./guestbook-shared";
import { ensureOperationsSchema } from "./operations-db";
import { getPostgresPool } from "./ranking-cache";

export type SheetMember = { rowIndex: number; crew_name: string; user_id: string; nickname: string; note: string; is_on_leave: boolean };
export type SheetAdmin = { login_id: string; password: string; crews: string[]; is_superadmin?: boolean; must_change_password?: boolean };
export type MemberRequestAction = "add" | "leave" | "restore" | "retire";
export type MemberRequestStatus = "pending" | "approved" | "rejected";
export type SheetMemberRequest = { rowIndex: number; action: MemberRequestAction; crew_name: string; user_id: string; nickname: string; status: MemberRequestStatus; requested_at: string; processed_by: string; processed_at: string };
export type NewMemberRequestInput = Pick<SheetMemberRequest, "action" | "crew_name" | "user_id" | "nickname">;
export class CrewVersionConflictError extends Error { constructor() { super("다른 기기에서 목록이 변경되었습니다. 새로고침 후 다시 시도해주세요."); this.name = "CrewVersionConflictError"; } }
async function db() { await ensureOperationsSchema(); const pool = getPostgresPool(); if (!pool) throw new Error("PostgreSQL 연결이 설정되지 않았습니다."); return pool; }
function member(row: Record<string, unknown>): SheetMember { const note=String(row.note??""); return { rowIndex:Number(row.id), crew_name:String(row.crew_name), user_id:String(row.user_id), nickname:String(row.nickname??""), note, is_on_leave:note.toLowerCase()==="휴직" }; }
export function computeCrewVersion(members: SheetMember[]) { return createHash("sha256").update(members.map(m=>`${m.crew_name}\t${m.user_id.toLowerCase()}\t${m.nickname}\t${m.note}`).sort().join("\n")).digest("hex").slice(0,16); }
export async function listMembers(crewName?: string) { const pool=await db(); const r=crewName ? await pool.query("SELECT id,crew_name,user_id,nickname,note FROM members WHERE lower(crew_name)=lower($1) ORDER BY id",[isFaCrew(crewName)?FA_CREW_NAME:crewName]) : await pool.query("SELECT id,crew_name,user_id,nickname,note FROM members ORDER BY id"); return r.rows.map(member); }
export async function getCrewMembersState(crew:string) { const members=await listMembers(crew); return {members,version:computeCrewVersion(members)}; }
export async function assertCrewVersion(crew:string, expected?:string) { if(expected && (await getCrewMembersState(crew)).version!==expected) throw new CrewVersionConflictError(); }
export async function findMember(crew:string,id:string) { return (await listMembers(crew)).find(m=>m.user_id.toLowerCase()===id.toLowerCase())??null; }
export async function findMemberByUserId(id:string) { const pool=await db(); const r=await pool.query("SELECT id,crew_name,user_id,nickname,note FROM members WHERE lower(user_id)=lower($1) LIMIT 1",[id]); return r.rows[0]?member(r.rows[0]):null; }
export async function findMembersByUserIds(ids:string[]) { const all=await listMembers(); const wanted=new Set(ids.map(x=>x.toLowerCase())); return new Map(all.filter(x=>wanted.has(x.user_id.toLowerCase())).map(x=>[x.user_id.toLowerCase(),x])); }
export async function listRegisteredCrewNames() { const pool=await db(); const r=await pool.query("SELECT crew_name FROM crews WHERE lower(crew_name)<>lower($1) ORDER BY crew_name",[FA_CREW_NAME]); return r.rows.map(x=>String(x.crew_name)); }
export async function listPublicCrewNames(){ return withFaCrew(await listRegisteredCrewNames()); }
export async function listAdmins(){ const pool=await db(); const r=await pool.query("SELECT login_id,password_hash,crews,is_superadmin,must_change_password FROM admins"); return r.rows.map(x=>({login_id:x.login_id,password:x.password_hash,crews:x.crews??[],is_superadmin:x.is_superadmin,must_change_password:x.must_change_password})); }
export function refreshGoogleSheetsCache() {}
export async function syncAdminsCrewColumns(_crews?: string[]){ return {updated:0}; }
export async function getAdmin(login:string){ return (await listAdmins()).find(x=>x.login_id===login)??null; }
export async function listAdminProfiles(){ const pool=await db(); const r=await pool.query("SELECT login_id,crews,is_superadmin,must_change_password FROM admins ORDER BY login_id"); return r.rows.map(x=>({login_id:String(x.login_id),crews:(x.crews??[]).map(String),is_superadmin:Boolean(x.is_superadmin),must_change_password:Boolean(x.must_change_password)})); }
export async function createAdmin(login:string,crews:string[]){ const id=login.trim(); if(!/^[a-zA-Z0-9_-]{3,30}$/.test(id)) throw new Error("아이디는 영문·숫자·밑줄·하이픈 3~30자로 입력해주세요."); const valid=new Set(await listRegisteredCrewNames()); const allowed=crews.filter(crew=>isFaCrew(crew)||valid.has(crew)); const pool=await db(); const {hashPassword}=await import("./operations-db"); await pool.query("INSERT INTO admins(login_id,password_hash,crews,is_superadmin,must_change_password) VALUES($1,$2,$3,FALSE,TRUE)",[id,hashPassword("1234"),allowed]); return {login_id:id,crews:allowed}; }
export async function addCrew(crew:string, representative:string){ const pool=await db(); await pool.query("INSERT INTO crews (crew_name,representative_name) VALUES ($1,$2) ON CONFLICT (crew_name) DO UPDATE SET representative_name=EXCLUDED.representative_name",[crew.trim(),representative.trim()]); }
export async function deleteCrew(crew:string){ if(isFaCrew(crew)) throw new Error("FA는 삭제할 수 없습니다."); const pool=await db(); const client=await pool.connect(); try { await client.query("BEGIN"); await client.query("UPDATE members SET crew_name=$1,updated_at=NOW() WHERE lower(crew_name)=lower($2)",[FA_CREW_NAME,crew]); await client.query("UPDATE admins SET crews=array_remove(crews,$1),updated_at=NOW()",[crew]); const result=await client.query("DELETE FROM crews WHERE lower(crew_name)=lower($1) RETURNING crew_name",[crew]); if(!result.rows[0]) throw new Error("크루를 찾을 수 없습니다."); await client.query("COMMIT"); } catch(error) { await client.query("ROLLBACK"); throw error; } finally { client.release(); } }
export async function addMember(crew:string,id:string,nick:string,version?:string){ await assertCrewVersion(crew,version); const pool=await db(); const old=await findMemberByUserId(id); if(old && !isFaCrew(old.crew_name)) throw new Error(`이미 ${old.crew_name} 크루에 등록된 스트리머입니다.`); await pool.query("INSERT INTO members (crew_name,user_id,nickname,note) VALUES ($1,$2,$3,'') ON CONFLICT (user_id) DO UPDATE SET crew_name=EXCLUDED.crew_name,nickname=EXCLUDED.nickname,note=''",[isFaCrew(crew)?FA_CREW_NAME:crew,id,nick]); }
export async function moveMemberToFa(crew:string,id:string,version?:string){ await assertCrewVersion(crew,version); const pool=await db(); await pool.query("UPDATE members SET crew_name=$1 WHERE lower(user_id)=lower($2) AND lower(crew_name)=lower($3)",[FA_CREW_NAME,id,crew]); }
export async function assignMembersFromFa(items:Array<{userId:string;targetCrew:string}>,version?:string){ await assertCrewVersion(FA_CREW_NAME,version); const pool=await db(); for(const x of items) await pool.query("UPDATE members SET crew_name=$1 WHERE lower(user_id)=lower($2) AND lower(crew_name)=lower($3)",[x.targetCrew,x.userId,FA_CREW_NAME]); return (await Promise.all(items.map(x=>findMemberByUserId(x.userId)))).filter((x):x is SheetMember=>Boolean(x)); }
export async function removeMemberPermanently(crew:string,id:string,version?:string){ await assertCrewVersion(crew,version); const pool=await db(); await pool.query("DELETE FROM members WHERE lower(user_id)=lower($1) AND lower(crew_name)=lower($2)",[id,crew]); }
export const deleteMember=moveMemberToFa;
export async function updateMemberNote(crew:string,id:string,note:string,version?:string){ await assertCrewVersion(crew,version); const pool=await db(); await pool.query("UPDATE members SET note=$1,updated_at=NOW() WHERE lower(user_id)=lower($2) AND lower(crew_name)=lower($3)",[note,id,crew]); }
export async function listMemberRequests(status?:MemberRequestStatus){ const pool=await db(); const r=await pool.query(`SELECT * FROM member_requests ${status?"WHERE status=$1":""} ORDER BY id DESC`,status?[status]:[]); return r.rows.map(x=>({rowIndex:Number(x.id),action:x.action,crew_name:x.crew_name,user_id:x.user_id,nickname:x.nickname,status:x.status,requested_at:new Date(x.requested_at).toISOString(),processed_by:x.processed_by,processed_at:x.processed_at?new Date(x.processed_at).toISOString():""})); }
export const listPendingMemberRequests=()=>listMemberRequests("pending");
export async function appendMemberRequests(items:NewMemberRequestInput[]){ const pool=await db(); const out=[] as SheetMemberRequest[]; for(const x of items){const r=await pool.query("INSERT INTO member_requests(action,crew_name,user_id,nickname) VALUES($1,$2,$3,$4) RETURNING *",[x.action,isFaCrew(x.crew_name)?FA_CREW_NAME:x.crew_name,x.user_id,x.nickname]); out.push((await listMemberRequests()).find(y=>y.rowIndex===Number(r.rows[0].id))!);} return out; }
export async function getMemberRequestsByRowIndexes(ids:number[]){ const all=await listMemberRequests(); return all.filter(x=>ids.includes(x.rowIndex)); }
export async function updateMemberRequestStatuses(ids:number[],status:Exclude<MemberRequestStatus,"pending">,by:string){ const pool=await db(); await pool.query("UPDATE member_requests SET status=$1,processed_by=$2,processed_at=NOW() WHERE id=ANY($3)",[status,by,ids]); }
type Entry={rowIndex:number;id:string;streamer_id:string;parent_id:string;author:string;body:string;created_at:string;password:string;password_salt:string;likes:number;dislikes:number;like_voters:string;dislike_voters:string};
function entry(x:Record<string,unknown>):Entry{return {rowIndex:0,id:String(x.id),streamer_id:String(x.streamer_id),parent_id:String(x.parent_id??""),author:String(x.author),body:String(x.body),created_at:new Date(String(x.created_at)).toISOString(),password:String(x.password),password_salt:String(x.password_salt??""),likes:Number(x.likes),dislikes:Number(x.dislikes),like_voters:String(x.like_voters??""),dislike_voters:String(x.dislike_voters??"")};}
export async function listGuestbookEntries(id?:string){const pool=await db();const r=await pool.query(`SELECT * FROM guestbook_entries ${id?"WHERE lower(streamer_id)=lower($1)":""} ORDER BY created_at`,id?[id]:[]);return r.rows.map(entry);}
export async function listGuestbookSummary(){const e=await listGuestbookEntries();const o:Record<string,{created_at:string;body:string}>={};for(const x of e)if(!x.parent_id&&(!o[x.streamer_id]||o[x.streamer_id].created_at<x.created_at))o[x.streamer_id]={created_at:x.created_at,body:x.body};return o;}
export async function findGuestbookEntry(id:string){return (await listGuestbookEntries()).find(x=>x.id===id)??null;}
export async function appendGuestbookEntry(x:Omit<Entry,"rowIndex"|"password_salt"|"likes"|"dislikes"|"like_voters"|"dislike_voters">){const pool=await db();await pool.query("INSERT INTO guestbook_entries(id,streamer_id,parent_id,author,body,created_at,password) VALUES($1,$2,$3,$4,$5,$6,$7)",[x.id,x.streamer_id,x.parent_id,x.author,x.body,x.created_at,x.password]);}
export async function updateGuestbookVote(id:string,voter:string,vote:GuestbookVote){const old=await findGuestbookEntry(id);if(!old)throw new Error("글을 찾을 수 없습니다.");const next=applyGuestbookVote(old,voter,vote);const pool=await db();await pool.query("UPDATE guestbook_entries SET likes=$1,dislikes=$2,like_voters=$3,dislike_voters=$4 WHERE id=$5",[next.likes,next.dislikes,next.like_voters,next.dislike_voters,id]);return {...old,...next};}
export async function deleteGuestbookEntries(id:string){const old=await findGuestbookEntry(id);if(!old)throw new Error("글을 찾을 수 없습니다.");const pool=await db();await pool.query("DELETE FROM guestbook_entries WHERE id=$1 OR parent_id=$1",[id]);return old;}
